Dt edits
CiscoCloud/mantl-devnet-learninglabs pull request #45
Opened 2019-12-09 09:19 UTC by dethanga

added a new file with instructions about deleting old instances of Docker container and images.

2019-12-09 09:23 UTC, dethanga commented
Hi Anne, 

I have added a new file (5.md) - To remove an existing Docker container and images.
I also updated the JSON file.

Please review and approve.

2019-12-10 16:31 UTC, annegentle requested changes
Minor suggestions inline - this is a great addition!

2019-12-10 16:31 UTC, annegentle commented on labs/docker-101/5.md
> +1. In the Windows PowerShell mode, run the following command to get the list of containers:
"In Windows PowerShell or a terminal window, run the following command to get the list of containers:"

2019-12-10 16:31 UTC, annegentle commented on labs/docker-101/5.md
> +    command to stop the process.
"Docker will not allow you to remove" < insert "you"

Or, "Docker prevents removal of a running container, so you need to use the `docker stop` command to stop the process before removing the instance."

2019-12-10 16:31 UTC, annegentle commented on labs/docker-101/5.md
> +3. To get the list of existing docker images, execute the following command:
docker > Docker

2019-12-10 16:31 UTC, annegentle commented on labs/docker-101/5.md
> +|docker build <path to docker file>|This command is used to build an image from a specified docker file.|
This table is wonderful! Nice work.

2019-12-11 14:01 UTC, merged